### ISSUE TITLE
Wallet support stopped working

### ISSUE THREAD

**Issue by Bluhme1** [nickknissen/hass-monta#127]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1455
Downloaded Repositories | 48

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 22. oktober 2024 kl. 02.00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-9.ui.nabu.casa
certificate_status | ready
instance_id | e95d96e84b464996bf5134c031bd5890
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.10.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 219.4 GB
disk_used | 148.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), File editor (5.8.0), Mosquitto broker (6.4.1), Advanced SSH & Web Terminal (19.0.0), Studio Code Server (5.17.2), Home Assistant Google Drive Backup (0.112.1), ESPHome (2024.10.0), RTSPtoWeb - WebRTC (1.4.0), Network UPS Tools (0.13.2), Zigbee2MQTT (1.40.2-1), Wmbusmeters (W-MBus to MQTT) (1.17.1), Music Assistant Server (beta) (2.3.0b33), Piper (1.5.2), Whisper (2.2.0), openWakeWord (1.10.0), Zigbee2MQTT Edge (edge), Docker Wyze Bridge (2.10.3), SQLite Web (4.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 25
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11. oktober 2024 kl. 18.45
-- | --
current_recorder_run | 21. oktober 2024 kl. 10.43
estimated_db_size | 2202.95 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

It seems that Monta has changed someting in their API making the wallet support fail. The integration has now been changed so that the whole integrations doesn't crash anymore but still unable to retrieve the wallet information.
Originally the feature was added by @RogerSelwyn so maybe he would care to have a lokk at it 

### Reproduction steps

1.none
2.
3.
...
none

### Debug logs

```text
none
```

### Diagnostics dump

none

**Comment by nickknissen** [comment]
@Bluhme1 You have to reach out to Monta support. 
The issue is that API response returns an error and there is nothing i can do in my side.

![image](https://github.com/user-attachments/assets/4e411f94-a1ed-4f2a-b905-43d3bc94113f)

**Comment by Bluhme1** [comment]
I have tried to contact Monta but they are very slow in responding

**Comment by RogerSelwyn** [comment]
I added the feature because it was requested by someone, I don’t use it myself. I could see that the api is returning an error, so I just disabled it in my code.

**Comment by Bluhme1** [comment]
Have been in contact with Monta again. And the API is fixed.
So everything is working again - including the wallet function
