### ISSUE TITLE
Inspiration from Zaptec

### ISSUE THREAD

**Issue by Bluhme1** [nickknissen/hass-monta#3]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No problem

### Describe the solution you'd like

I am currently using the Zaptec integration 
https://github.com/custom-components/zaptec
There is a lot of information (perhaps also too much) but I enclose a picture of my installation as an inspiration.
I realize that the API is currently limited and doesn’t supply all this information but consider this as an attempt to inspire the future works
And thank you very much for your work.
/Lars
![IMG_1134](https://github.com/nickknissen/hass-monta/assets/50340474/347b74dc-2c78-42ae-9c05-85ea249b85f2)

### Describe alternatives you've considered

See above

### Additional context

See above

**Comment by Bluhme1** [comment]
@nickknissen Hi Nick
Just to let you know, I have been using your integration for the last week on a daily basis. And it works great.
I use the binary_sensor - "plugged-in" and the switch - on/off in automations that start charging when the price is lowest. (using Energi Data Service).
I have looked into the API and it would be great to have some sensors concerning the charger session. (See below). Having these would make it possible to create some statistics on the charging situation.

And - in the long run - also sensors concerning the wallet functionality to make it possible to decide the actual price of charging. 

You were asking for feed-back and testing, so here you go

/Lars

      "consumedKwh": 0,
      "kwhLimit": null,
      "startMeterKwh": 0,
      "endMeterKwh": 0,
      "price": 0,
      "priceLimit": null,
      "averagePricePerKwh": 0,
      "averageCo2PerKwh": 0,
      "averageRenewablePerKwh": 0,

**Comment by nickknissen** [comment]
Thanks for the feedback, Sorry i havent answered before, but have been on vacation.
You have provided me with great suggestions.

I think the next thing i will look into implementing is providing the current charge session.

**Comment by Bluhme1** [comment]
@nickknissen Great. Looking forward. I am ready to test.

**Comment by Bluhme1** [comment]
@nickknissen 
Hi again Nick. Just for your information. The "charges-part" of the API seems to lack some information - as far as I can see. 

I have raised a question at https://docs.public-api.monta.com/discuss/64d36f782d32be004d190ad8. But no answer yet.

To make the API useful, it is af course necessary that it is populated with the relevant information. I think it is safe to continue developing on your integration as it must be expected that the rigt data eventually will be provided in the development of the API.

How are things progressing?

**Comment by plaiddk** [comment]
Sorry to interrupt this message but @Bluhme1  could you perhaps share your setup regarding zaptec? I have the same thing. Or maybe we could continue "chatting" somewhere else? Im concerned if I use zaptec integration my monta app will break down. 

And thanks to @nickknissen  for making this possible also!

**Comment by Bluhme1** [comment]
Monta integration working just fine. New functionalities must await an update of the Monta Public API
Closing
