### ISSUE TITLE
Not a bug but a question

### ISSUE THREAD

**Issue by Bluhme1** [nickknissen/hass-monta#54]
### System Health details

None

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

During the last few days I have lost connection to the API periodically. It means that the number in sensor.*.last_charge attribute "consumedKwh" is reset to zero for a short moment.
I use this number in my utility meter calculating Kwh pr.  day, pr week, pr. month and pr. year and this calculating is destroyed because the Utility Meter sees the difference between zero and the actual consumption and adds it to the number. I could make a template that filters out any readings of zero but when a charge is started it will start with zero and I - of course - don't want to filter that out.
I could also use the Last_meter_reading as source for my Utility Meters but then I lose the possibility to do calculations of the actual price using the attribute "cost" as a source for my Utility Meters.

Has any of you experienced the same behaviour and perhaps has a good advice for solving it?

### Reproduction steps

1.
2.
3.
...
None

### Debug logs

```text
None
```

### Diagnostics dump

None

**Comment by nickknissen** [comment]
Do you have [periodically resetting](https://www.home-assistant.io/integrations/utility_meter/#periodically-resetting) enabled on the utility Meter? That should help migate the zero values when the sensor becomes unavailable and the value becomes zero

**Comment by Bluhme1** [comment]
Nothing to do with this integration. Closing
