### ISSUE TITLE
Error Encountered: 'Invalid Credentials' When Adding Integration via GUI

### ISSUE THREAD

**Issue by antonraptor** [nickknissen/hass-monta#55]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4109
Installed Version | 1.34.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 71

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 30. Dezember 2024 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-17.ui.nabu.casa
certificate_status | ready
instance_id | 22474fab51a34d46bd68ec124bae3b84
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 27.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Mosquitto broker (6.4.0), Samba share (12.2.0), Terminal & SSH (9.8.1), AirCast (4.2.0), Home Assistant Google Drive Backup (0.112.1), Silicon Labs Multiprotocol (2.4.4), MariaDB (2.6.1), Grocy (0.21.0), Ring-MQTT with Video Streaming (5.6.3), openWakeWord (1.8.2), Whatsapp (1.3.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 52
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. Januar 2024 um 08:04
-- | --
current_recorder_run | 25. Januar 2024 um 14:51
estimated_db_size | 2348.34 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I encountered an "invalid credentials" error while attempting to add an integration via the GUI.

To set up the integration, I followed the documentation provided for creating an application in CPMS, which can be found here: [CPMS Application Setup](https://docs.public-api.monta.com/reference/home).

I successfully created a new application and obtained both the clientID and clientSecret. Additionally, I was able to obtain an accessToken as described in the documentation [here](https://docs.public-api.monta.com/reference/get-access-token-with-client-credentials).

Despite obtaining these credentials and verifying their functionality, I continue to face the "invalid credentials" error when attempting to integrate via the GUI.

### Reproduction steps

1. Navigate to the CPMS documentation at [CPMS Documentation](https://docs.public-api.monta.com/reference/home).

2. Follow the provided documentation to create a new application in CPMS, ensuring that you note down both the clientID and clientSecret for the integration.

3. Refer to the documentation on obtaining an accessToken via the following link: [Get Access Token with Client Credentials](https://docs.public-api.monta.com/reference/get-access-token-with-client-credentials), and successfully retrieve an accessToken.

4. With the obtained clientID, clientSecret attempt to add the integration via the GUI.

5. Observe that an "invalid credentials" error is encountered during the integration process.

### Debug logs

```text
2024-01-25 15:19:25.181 DEBUG (MainThread) [custom_components.monta.api] [auth/token] Response header: <CIMultiDictProxy('Date': 'Thu, 25 Jan 2024 14:19:25 GMT', 'Content-Type': 'application/json', 'Content-Length': '267', 'Connection': 'keep-alive', 'request-id': 'SECRET', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains')>
2024-01-25 15:19:25.181 DEBUG (MainThread) [custom_components.monta.api] [auth/token] Response status: 200
2024-01-25 15:19:25.181 DEBUG (MainThread) [custom_components.monta.api] [auth/token] Response body : {'applicationId': 251, 'userId': 300826, 'accessToken': '************************************', 'accessTokenExpirationDate': '2024-01-25T15:19:25.157995237Z', 'refreshToken': '************************************', 'refreshTokenExpirationDate': '2024-02-24T14:19:25.157996252Z'}
2024-01-25 15:19:25.183 DEBUG (MainThread) [custom_components.monta.api] Refresh Token still valid, using it
2024-01-25 15:19:25.231 DEBUG (MainThread) [custom_components.monta.api] [auth/refresh] Response header: <CIMultiDictProxy('Date': 'Thu, 25 Jan 2024 14:19:25 GMT', 'Content-Type': 'application/json', 'Content-Length': '155', 'Connection': 'keep-alive', 'request-id': 'SECRET', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains')>
2024-01-25 15:19:25.231 DEBUG (MainThread) [custom_components.monta.api] [auth/refresh] Response status: 401
2024-01-25 15:19:25.231 DEBUG (MainThread) [custom_components.monta] Finished fetching monta data in 0.050 seconds (success: False)
2024-01-25 15:19:25.231 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Monta account 300826' for monta integration could not authenticate: Invalid credentials
```

**Comment by nickknissen** [comment]
Looks like same issue as @Neesgaard in https://github.com/nickknissen/hass-monta/issues/52.    
You get an a valid accessToken and refreshToken back from the API, but there might be a timezone bug which causes it to fetch a new accessToken before the refreshToken is valid.

Can you verify that https://docs.public-api.monta.com/reference/get-access-token-with-refresh-token works with your generated refresh token when you use their UI?

**Comment by antonraptor** [comment]
Yes, I can verify that the provided hat _"Obtain your `accessToken` with a `refreshToken`"_ works with by generated refresh token.

**Comment by nickknissen** [comment]
@antonraptor Could you test the new pre release? [v1.3.1](https://github.com/nickknissen/hass-monta/releases/tag/v.1.3.1)  
There is a bug where the refresh token is stored between installations and causes problems when using a new client id/secret

**Comment by antonraptor** [comment]
@nickknissen Just updated, restarted HA and integration is working again - great & thank you! 👍

**Comment by antonraptor** [comment]
@nickknissen Just updated, restarted HA and integration is working again - great & thank you! 👍
