### ISSUE TITLE
add project to HACS to make updating it easier. 

### ISSUE THREAD

**Issue by AndersV209** [nickknissen/hass-monta#56]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

add project to HACS to make updating it easier. (and to be easier for people to find) 

### Describe alternatives you've considered

none

### Additional context

none

**Comment by StefanLobbenmeier** [comment]
Can we also add this to the readme that this is now an option for installation?
