### ISSUE TITLE
FYI. The API is broken. "Cost" field is populated with random number when charge starts

### ISSUE THREAD

**Issue by Bluhme1** [nickknissen/hass-monta#61]
### System Health details

none

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

@nickknissen 
When I start a charge through the API the "cost" field in the API starts with a hig, random number. It destroys my readings in my Utility Meters reporting the price of charging pr. day, week, etc.
I have reported it to the API discussion. https://docs.public-api.monta.com/discuss/65c7a2ca05c695005fe0752b

Just for your information, so that you don't spent hours investigating like I did.

/Lars

### Reproduction steps

1.
2.
3.
...
none

### Debug logs

```text
none
```

### Diagnostics dump

none

**Comment by cweinberger** [comment]
FYI this should be fixed as of today ~2pm

**Comment by Bluhme1** [comment]
Fixed. Thank you very much
