### ISSUE TITLE
Integrate "forecasts" (incl. "7-day forecass")

### ISSUE THREAD

**Issue by Aephir** [nickknissen/hass-monta#62]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not a problem, more of an "upgrade".

### Describe the solution you'd like

It would be great, if possible, to expose some of the "forecasts" that are available in the Monta App.

In particular:
1. The "7-day electricity price" (gives a best-guess hour-by-hour price for the next seven days --> Great for deciding whether to skip charging for a few nights).
2. The "CO2-level" (gives the least CO2-intensive times to use power)
3. The "Percentage renewable" (as the name implies, hour for hour)

### Describe alternatives you've considered

None that I know how to integrate in Home Assistant.

### Additional context

None

**Comment by Boggie** [comment]
I use the "Energi Data Service" integration for this (https://github.com/MTrab/energidataservice, available in HACS).
As it states: "The integration adds posibility to get a 5 day price forecast for the next week thru carnot.dk"

From what I can see, the forecast I get via this matches pretty well with Monta.

**Comment by Aephir** [comment]
That's great for the forecast (which, to be honest, was the most useful of them). Thanks!

**Comment by nickknissen** [comment]
@Aephir Unfortunately the api exposed by Monta does not include the data, but as @Boggie mentions https://github.com/MTrab/energidataservice include forcast via carnot. 

CO2 sensor has also been added to energidataservice

![image](https://github.com/nickknissen/hass-monta/assets/204970/03eb1f66-1917-4650-b13d-15ab0f2d9908)

If at some point monta exposes more data via the API i will look into the this feature. For now i will close the issue
